### ISSUE TITLE
Same timezone in multiple countries

### ISSUE THREAD

**Issue by fuelen** [mathieuprog/tz_extra#7]
I'm in progress of updating the library from v0.20.1, and I noticed, that in old version I receive 1 item for Europe/Berlin
```elixir
> TzExtra.countries_time_zones() |> Enum.filter(& &1.time_zone == "Europe/Berlin")
[
  %{
    coordinates: "+5230+01322",
    country: %{code: "DE", name: "Germany"},
    dst_offset: 7200,
    dst_zone_abbr: "CEST",
    pretty_dst_offset: "+02:00",
    pretty_utc_offset: "+01:00",
    time_zone: "Europe/Berlin",
    time_zone_links: [],
    utc_offset: 3600,
    zone_abbr: "CET"
  }
]
```
And this is what I receive with v0.24.0
```elixir
> TzExtra.countries_time_zones() |> Enum.filter(& &1.time_zone == "Europe/Berlin")
[
  %{
    coordinates: "+5230+01322",
    country: %{code: "DK", name: "Denmark"},
    dst_offset: 7200,
    dst_zone_abbr: "CEST",
    pretty_dst_offset: "+02:00",
    pretty_utc_offset: "+01:00",
    time_zone: "Europe/Berlin",
    time_zone_links: ["Atlantic/Jan_Mayen", "Europe/Stockholm", "Europe/Oslo",
     "Europe/Copenhagen", "Arctic/Longyearbyen"],
    utc_offset: 3600,
    zone_abbr: "CET"
  },
  %{
    coordinates: "+5230+01322",
    country: %{code: "DE", name: "Germany"},
    dst_offset: 7200,
    dst_zone_abbr: "CEST",
    pretty_dst_offset: "+02:00",
    pretty_utc_offset: "+01:00",
    time_zone: "Europe/Berlin",
    time_zone_links: ["Atlantic/Jan_Mayen", "Europe/Stockholm", "Europe/Oslo",
     "Europe/Copenhagen", "Arctic/Longyearbyen"],
    utc_offset: 3600,
    zone_abbr: "CET"
  },
  %{
    coordinates: "+5230+01322",
    country: %{code: "NO", name: "Norway"},
    dst_offset: 7200,
    dst_zone_abbr: "CEST",
    pretty_dst_offset: "+02:00",
    pretty_utc_offset: "+01:00",
    time_zone: "Europe/Berlin",
    time_zone_links: ["Atlantic/Jan_Mayen", "Europe/Stockholm", "Europe/Oslo",
     "Europe/Copenhagen", "Arctic/Longyearbyen"],
    utc_offset: 3600,
    zone_abbr: "CET"
  },
  %{
    coordinates: "+5230+01322",
    country: %{code: "SJ", name: "Svalbard & Jan Mayen"},
    dst_offset: 7200,
    dst_zone_abbr: "CEST",
    pretty_dst_offset: "+02:00",
    pretty_utc_offset: "+01:00",
    time_zone: "Europe/Berlin",
    time_zone_links: ["Atlantic/Jan_Mayen", "Europe/Stockholm", "Europe/Oslo",
     "Europe/Copenhagen", "Arctic/Longyearbyen"],
    utc_offset: 3600,
    zone_abbr: "CET"
  },
  %{
    coordinates: "+5230+01322",
    country: %{code: "SE", name: "Sweden"},
    dst_offset: 7200,
    dst_zone_abbr: "CEST",
    pretty_dst_offset: "+02:00",
    pretty_utc_offset: "+01:00",
    time_zone: "Europe/Berlin",
    time_zone_links: ["Atlantic/Jan_Mayen", "Europe/Stockholm", "Europe/Oslo",
     "Europe/Copenhagen", "Arctic/Longyearbyen"],
    utc_offset: 3600,
    zone_abbr: "CET"
  }
]
```

all the entities above have the same `:time_zone` and `:time_zone_links`

**Comment by mathieuprog** [comment]
Dang I missed that issue, just got aware of it now. Looking into it!

**Comment by mathieuprog** [comment]
0.20.1 was using 2021a, with 0.24.0 you are using 2022f.

The IANA zone1970.tab file holds the mapping country <-> time zone.

For 2021a:
https://data.iana.org/time-zones/tzdb-2021a/zone1970.tab

For 2022f:
https://data.iana.org/time-zones/tzdb-2022f/zone1970.tab

Search for "Europe/Berlin", you may see that there is a change which is self-explanatory.

**Comment by mathieuprog** [comment]
Btw the docs mention
> Note that a time zone may be observed by multiple countries.

So your code must expect such changes after updating the IANA time zone data.

**Comment by mathieuprog** [comment]
Also would be nice to know in what issue you run, if any. Just curious:) sometimes discussions of needs can lead to enhancements.

**Comment by fuelen** [comment]
> Also would be nice to know in what issue you run, if any. Just curious:) sometimes discussions of needs can lead to enhancements.

We have timezones of people in database, and we try to detect a country by timezone in order to provide local phone numbers for them.
So, when someone has timezone Europe/Oslo it is very unlikely that he is from Berlin, and vice versa :)

**Comment by mathieuprog** [comment]
Okay but that can only be a guess.

Btw I do the same thing in JS:) but based on time zone + the user's preferred language tags in the browser.
https://github.com/mathieuprog/user-locale#country

**Comment by mathieuprog** [comment]
I think it's probably better not to guess on time zone alone, might worsen the UX. Just food for thought:)
